[tool.poetry]
name = "skq"
version = "0.1.0"
description = "Convenient Quantum Components"
authors = ["Carlo Lepelaars"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.1"

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6.0"
pytest = "^8.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
