[tool.poetry]
name = "scikit-q"
version = "0.1.0"
description = ""
authors = ["Carlo Lepelaars <info@carlolepelaars.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
scikit-learn = "^1.5.1"

[tool.poetry.group.dev.dependencies]
mkdocs = "^1.6.0"
pytest = "^8.2.2"

[tool.poetry.packages]
skq = { from = "skq" }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
